### ISSUE TITLE
Update parent/parentOf field in characters.json

### ISSUE THREAD

**Issue by vitome** [jeffreylancaster/game-of-thrones#4]
Hi Jeffrey, you're project is very interesting and I thank you for the nice work. I was trying to use the data/characters.json file in a small project to visualize the genealogical trees, but I'm finding some missing connections... Or maybe I'm simply overlooking something, please help me: for example, if you pick the character "Eddard Stark", he should should be the father of Robb Stark, Sansa Stark, Arya Stark, and Bran Stark, but in the json file you cannot find any relation between them: the parent/parentOf relation seems incomplete. Do you think I am missing something, or there is some issue that I should fix?

**Comment by jeffreylancaster** [comment]
You're absolutely right! I've not done much with the parent/parentOf field in `characters.json` really, so it's certainly not as fully connected as it ought to be. If there are particular characters you're wanting to include in the family tree, please let me know - I'm happy to add that info. Or feel free to update that file and PR it. Thanks for flagging that!

**Comment by jeffreylancaster** [comment]
Actually, I'll take a look at this soon - I've been meaning to update that file 👍
