### ISSUE TITLE
Any license for the data?

### ISSUE THREAD

**Issue by eoinmurray** [jeffreylancaster/game-of-thrones#6]
Seems like it would be really fun to play with - but is it copyright for yourself?

**Comment by jeffreylancaster** [comment]
Hey Eoin! Feel free to have a play with it - no license restrictions at all. I just ask that you let me know what you end up doing with it and cite this repo if you end up publishing something. I should probably document that somewhere... Thanks for asking!

**Comment by eoinmurray** [comment]
Thats great - at kyso we sometimes run little competitions in our community where we send out a dataset and see what people come up with - this seems like a really cool one to play with - we will cite this repo in the post and ask our community members do also

**Comment by jeffreylancaster** [comment]
Awesome! Looking forward to seeing what they come up with.
